language: node_js
node_js:
- '8'
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 92.53.91.116>> ~/.ssh/known_hosts
- chmod 600 ../../lastunion_key
- ssh-add ../../lastunion_key
- npm run generate_bundle
- scp -r ./public root@92.53.91.116:/var/www
- ssh root@92.53.91.116 << EOF
- cd /var/www/public
- uglifycss css/style.css --output css/style.css
- uglifyjs bundle.js -o bundle.js
- EOF
before_install:
- openssl aes-256-cbc -K $encrypted_402e7d50a36d_key -iv $encrypted_402e7d50a36d_iv
  -in lastunion_key.enc -out ../../lastunion_key -d
