language: node_js
node_js:
- '8'
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 92.53.91.116>> ~/.ssh/known_hosts
- chmod 600 ../../lastunion_key
- ssh-add ../../lastunion_key
- npm run generate_bundle
- scp -r ./public root@92.53.91.116:/var/www
- ssh root@92.53.91.116 'uglifycss /var/www/public/css/style.css --output /var/www/public/css/style.css | uglifyjs /var/www/public/bundle.js -o /var/www/public/bundle.js | ./node_start.sh'
before_install:
- openssl aes-256-cbc -K $encrypted_402e7d50a36d_key -iv $encrypted_402e7d50a36d_iv
  -in lastunion_key.enc -out ../../lastunion_key -d
